channels:
- bioconda
- conda-forge
- file:///local_channel
- defaults
dependencies:
- bioconductor-annotate==1.72.0
- bioconductor-annotationdbi==1.56.2
- bioconductor-beachmat==2.10.0
- bioconductor-biobase==2.54.0
- bioconductor-biocgenerics==0.40.0
- bioconductor-biocparallel==1.28.3
- bioconductor-biocsingular==1.10.0
- bioconductor-biostrings==2.62.0
- bioconductor-complexheatmap==2.10.0
- bioconductor-delayedarray==0.20.0
- bioconductor-delayedmatrixstats==1.16.0
- bioconductor-edger==3.36.0
- bioconductor-fgsea==1.20.0
- bioconductor-genefilter==1.76.0
- bioconductor-genomeinfodb==1.30.1
- bioconductor-genomeinfodbdata==1.2.6
- bioconductor-genomicranges==1.46.1
- bioconductor-graph==1.72.0
- bioconductor-gseabase==1.56.0
- bioconductor-gsva==1.42.0
- bioconductor-hdf5array==1.22.1
- bioconductor-iranges==2.28.0
- bioconductor-keggrest==1.34.0
- bioconductor-limma==3.50.3
- bioconductor-matrixgenerics==1.6.0
- bioconductor-rhdf5==2.38.1
- bioconductor-rhdf5filters==1.6.0
- bioconductor-rhdf5lib==1.16.0
- bioconductor-s4vectors==0.32.4
- bioconductor-scaledmatrix==1.2.0
- bioconductor-singlecellexperiment==1.16.0
- bioconductor-sparsematrixstats==1.6.0
- bioconductor-summarizedexperiment==1.24.0
- bioconductor-sva==3.42.0
- bioconductor-xvector==0.34.0
- bioconductor-zlibbioc==1.40.0
- r-amap==0.8_19
- r-arrow==5.0.0
- r-askpass==1.1
- r-assertthat==0.2.1
- r-backports==1.4.1
- r-base64enc==0.1_3
- r-base==4.1.3
- r-bh==1.81.0_1
- r-biocmanager
- r-bit64==4.0.5
- r-bit==4.0.5
- r-bitops==1.0_7
- r-blob==1.2.4
- r-broom==1.0.4
- r-bslib==0.4.2
- r-ca==0.71.1
- r-cachem==1.0.7
- r-callr==3.7.3
- r-catools==1.18.2
- r-cellranger==1.1.0
- r-circlize==0.4.15
- r-cli==3.6.1
- r-clipr==0.8.0
- r-clue==0.3_64
- r-cluster==2.1.4
- r-codetools==0.2_19
- r-colorspace==2.1_0
- r-commonmark==1.9.0
- r-conflicted==1.2.0
- r-cpp11==0.4.3
- r-crayon==1.5.2
- r-crosstalk==1.2.0
- r-curl==4.3.3
- r-data.table==1.14.8
- r-dbi==1.1.3
- r-dbplyr==2.3.2
- r-dendextend==1.17.1
- r-dendsort==0.3.4
- r-digest==0.6.31
- r-doparallel==1.0.17
- r-dplyr==1.1.1
- r-dtplyr==1.3.1
- r-egg==0.4.5
- r-ellipsis==0.3.2
- r-evaluate==0.20
- r-fansi==1.0.4
- r-farver==2.1.1
- r-fastmap==1.1.1
- r-fastmatch==1.1_3
- r-fontawesome==0.5.0
- r-forcats==1.0.0
- r-foreach==1.5.2
- r-formatr==1.14
- r-fs==1.6.1
- r-futile.logger==1.4.3
- r-futile.options==1.0.1
- r-gargle==1.3.0
- r-gclus==1.3.2
- r-generics==0.1.3
- r-getoptlong==1.0.5
- r-ggplot2==3.4.2
- r-ggrepel==0.9.3
- r-globaloptions==0.1.2
- r-glue==1.6.2
- r-googledrive==2.1.0
- r-googlesheets4==1.1.0
- r-gplots==3.1.3
- r-gridextra==2.3
- r-gridgraphics==0.5_1
- r-gtable==0.3.3
- r-gtools==3.9.4
- r-haven==2.5.2
- r-heatmaply==1.4.2
- r-hexbin==1.28.3
- r-highr==0.10
- r-hms==1.1.3
- r-htmltools==0.5.5
- r-htmlwidgets==1.6.2
- r-httr==1.4.5
- r-ids==1.0.1
- r-irlba==2.3.5.1
- r-isoband==0.2.7
- r-iterators==1.0.14
- r-jquerylib==0.1.4
- r-jsonlite==1.8.4
- r-kernsmooth==2.23_20
- r-knitr==1.42
- r-l2p==0.0_13
- r-l2psupp==0.0_13
- r-labeling==0.4.2
- r-lambda.r==1.2.4
- r-later==1.3.0
- r-lattice==0.21_8
- r-lazyeval==0.2.2
- r-lifecycle==1.0.3
- r-locfit==1.5_9.7
- r-lubridate==1.9.2
- r-magrittr==2.0.3
- r-markdown==1.5
- r-mass==7.3_58.3
- r-matrix==1.5_4
- r-matrixstats==0.63.0
- r-memoise==2.0.1
- r-mgcv==1.8_42
- r-mime==0.12
- r-modelr==0.1.11
- r-munsell==0.5.0
- r-nidapfunctions==0.7.8
- r-nlme==3.1_162
- r-openssl==2.0.5
- r-patchwork==1.1.2
- r-pheatmap==1.0.12
- r-pillar==1.9.0
- r-pkgconfig==2.0.3
- r-plogr==0.2.0
- r-plotly==4.10.1
- r-plotrix==3.8_2
- r-plyr==1.8.8
- r-png==0.1_8
- r-prettyunits==1.1.1
- r-processx==3.8.0
- r-progress==1.2.2
- r-promises==1.2.0.1
- r-ps==1.7.4
- r-purrr==1.0.1
- r-qap==0.1_2
- r-r6==2.5.1
- r-ragg==1.2.5
- r-rappdirs==0.3.3
- r-rcolorbrewer==1.1_3
- r-rcpp==1.0.10
- r-rcurl==1.98_1.12
- r-readr==2.1.4
- r-readxl==1.4.2
- r-registry==0.5_1
- r-rematch2==2.1.2
- r-rematch==1.0.1
- r-renv
- r-renv==0.17.3
- r-reprex==2.0.2
- r-reshape2==1.4.4
- r-reshape==0.8.9
- r-rjson==0.2.21
- r-rlang==1.1.0
- r-rmarkdown==2.21
- r-rsqlite==2.3.1
- r-rstudioapi==0.14
- r-rsvd==1.0.5
- r-rvest==1.0.3
- r-sass==0.4.5
- r-scales==1.2.1
- r-selectr==0.4_2
- r-seriation==1.4.2
- r-shape==1.4.6
- r-snow==0.4_4
- r-statmod==1.5.0
- r-stringi==1.7.12
- r-stringr==1.5.0
- r-survival==3.5_5
- r-survminer==0.4.9
- r-svglite==2.1.1
- r-svmisc==1.2.3
- r-sys==3.4.1
- r-systemfonts==1.0.4
- r-textshaping==0.3.6
- r-tibble==3.2.1
- r-tidyr==1.3.0
- r-tidyselect==1.2.0
- r-tidyverse==2.0.0
- r-timechange==0.2.0
- r-tinytex==0.44
- r-tsp==1.2_4
- r-tzdb==0.3.0
- r-upsetr==1.4.0
- r-utf8==1.2.3
- r-uuid==1.1_0
- r-vctrs==0.6.1
- r-venndiagram==1.7.3
- r-viridis==0.6.2
- r-viridislite==0.4.1
- r-vroom==1.6.1
- r-webshot==0.5.4
- r-withr==2.5.0
- r-xfun==0.38
- r-xml2==1.3.3
- r-xml==3.99_0.14
- r-xtable==1.8_4
- r-yaml==2.3.7
name: bulk-rna-seq
